name: Generate Ecosystem Deposit CSVs

on:
  schedule:
    - cron: "* * * * *"

jobs:
  generate-csv-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: action-results

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Generate CSV
        run: |
          # If this is a cron job, use the most recent midnight UTC.
          if [ "$GITHUB_EVENT_NAME" == "schedule" ]; then
              current_date_utc=$(date -u "+%Y-%m-%d")
              midnight_utc=$(date -ud "$current_date_utc" +%s)
              export TIMESTAMP="$midnight_utc"
          fi
          pip3 install -r requirements.txt
          python ./generate_ecosystem_deposits.py
          git config --global user.email "maxis@balancer.rocks"
          git config --global user.name "Github Action"
          git add -A
          git commit -m "Github actions run - time: $TIMESTAMP,  block: $BLOCK, pool_id: $POOL_ID"
          git push origin action-results
