name: Generate Ecosystem Deposits V2 (multipool)

on:
  workflow_dispatch:
    inputs:
      POOL_ID:
        description: "The pool_id of the pool to query, must match a pool in run_pools.json, leave blank for all"
      BLOCK:
        description: "The block number to measure at, if unset will use timestamp."
      TIMESTAMP:
        description: "A timestamp to take the next block after if BLOCK is undefined, if also undefined will use 5 minutes ago."
  schedule:
    - cron: "*/5 * * * *"


jobs:
  generate-csvs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ref: action-results

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Generate CSV
        env:
          POOL_ID: ${{ github.event.inputs.POOL_ID }}
          TIMESTAMP: ${{ github.event.inputs.GAUGE }}
          BLOCK: ${{ github.event.inputs.BLOCK }}
        run: |
          ## If no timestamp is provided, use the most recent midnight UTC.
          if [ -z "$TIMESTAMP" ]; then
              current_date_utc=$(date -u "+%Y-%m-%d")              
              midnight_utc=$(date -ud "$current_date_utc" +%s)
              export TIMESTAMP="$midnight_utc"          
          pip3 install -r requirements.txt
          python ./generate_ecosystem_deposits.py
          git commit -A
          git push origin action-results
